import '../packages/stencil-library/src/tailwind.css';

// Register all components using Stencil's lazy-loading entry point.
// This is always available (produced by both dev and production builds),
// unlike dist-custom-elements which is only generated by `stencil build`.
import '../packages/stencil-library/dist/pid-component/pid-component.esm.js';

export default {
  parameters: {
    a11y: {
      context: {},
      config: {},
      options: {},
    },
    backgrounds: {
      options: {
        dark: { name: 'Dark', value: '#222' },
        light: { name: 'Light', value: '#F7F9F2' },
      },
    },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
  tags: ['autodocs'],
};
