/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * This component highlights a handle and links to the FAIR DO Scope.
     * It automatically generates colors for the parts of the handle (prefix and suffix) to make them easily distinguishable.
     */
    interface HandleHighlight {
        /**
          * Whether the component should use the filled or the outlined design.
         */
        "filled": boolean;
        /**
          * The Handle to highlight and link in this component.
         */
        "handle": string;
        /**
          * An optional custom link to use instead of the default one which links to the FAIR DO Scope.
         */
        "linkTo": "disable" | "fairdoscope" | "resolveRef";
    }
}
declare global {
    /**
     * This component highlights a handle and links to the FAIR DO Scope.
     * It automatically generates colors for the parts of the handle (prefix and suffix) to make them easily distinguishable.
     */
    interface HTMLHandleHighlightElement extends Components.HandleHighlight, HTMLStencilElement {
    }
    var HTMLHandleHighlightElement: {
        prototype: HTMLHandleHighlightElement;
        new (): HTMLHandleHighlightElement;
    };
    interface HTMLElementTagNameMap {
        "handle-highlight": HTMLHandleHighlightElement;
    }
}
declare namespace LocalJSX {
    /**
     * This component highlights a handle and links to the FAIR DO Scope.
     * It automatically generates colors for the parts of the handle (prefix and suffix) to make them easily distinguishable.
     */
    interface HandleHighlight {
        /**
          * Whether the component should use the filled or the outlined design.
         */
        "filled"?: boolean;
        /**
          * The Handle to highlight and link in this component.
         */
        "handle": string;
        /**
          * An optional custom link to use instead of the default one which links to the FAIR DO Scope.
         */
        "linkTo"?: "disable" | "fairdoscope" | "resolveRef";
    }
    interface IntrinsicElements {
        "handle-highlight": HandleHighlight;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * This component highlights a handle and links to the FAIR DO Scope.
             * It automatically generates colors for the parts of the handle (prefix and suffix) to make them easily distinguishable.
             */
            "handle-highlight": LocalJSX.HandleHighlight & JSXBase.HTMLAttributes<HTMLHandleHighlightElement>;
        }
    }
}
