/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { FoldableAction } from './utils/FoldableAction';
import { FoldableItem } from './utils/FoldableItem';

export { FoldableAction } from './utils/FoldableAction';
export { FoldableItem } from './utils/FoldableItem';
export namespace Components {
    interface ColorHighlight {
        /**
          * The text to highlight.
          * @type {string}
         */
        "text": string;
    }
    interface CopyButton {
        /**
          * The value to copy to the clipboard.
          * @type {string}
          * @public
         */
        "value": string;
    }

  interface JsonViewer {
    /**
     * Collapse all nodes in the tree view
     */
    collapseAllNodes: () => Promise<void>;
    /**
     * The JSON data to display. Can be a JSON string or a JavaScript object.
     */
    data: string | object;
    /**
     * Set to true to open all nodes in tree view initially.
     * @default false
     */
    expandAll: boolean;
    /**
     * Expand all nodes in the tree view
     */
    expandAllNodes: () => Promise<void>;
    /**
     * Maximum height of the viewer in pixels. Set to 0 for no limit.
     * @default 500
     */
    maxHeight: number;
    /**
     * Set to true to enable line numbers in code view.
     * @default true
     */
    showLineNumbers: boolean;
    /**
     * Theme for syntax highlighting. Options: 'light' or 'dark'.
     * @default 'light'
     */
    theme: 'light' | 'dark';
    /**
     * Initial view mode for the JSON data. Can be 'tree' or 'code'.
     * @default 'tree'
     */
    viewMode: 'tree' | 'code';
  }
    interface LocaleVisualization {
      /**
       * The locale to visualize.
       * @type {string}
       * @public
       */
      "locale": string'locale'/**
       * Whether to show the flag of the region.
       * @type {boolean}
       * @public
       * @default true
       */
      "showFlag": bool'showFlag'

  interface PidActions {
    /**
     * Array of actions to display
     * @default []
     */
    "actions": Folda'actions'[];
  }

  interface PidCollapsible {
    /**
     * Whether to emphasize the component with border and shadow
     * @default false
     */
    "emphasize": boo'emphasize'**
     * Whether the component is in expanded mode (full size)
     * @default false
     */
    "expanded": bool'expanded'**
     * Initial height when expanded
     */
    "initialHeight"?'initialHeight'**
     * Initial width when expanded
     */
    "initialWidth"?:'initialWidth'**
     * Line height for collapsed state
     * @default 24
     */
    "lineHeight": nu'lineHeight'*
     * Whether the collapsible is open by default
     * @default false
     */
    "open": boolean;'open'**
     * Whether to show the footer section
     * @default false
     */
    "showFooter": bo'showFooter'  interface PidComponent {
    /**
     * The number of items to show in the table per page. Defaults to 10. (optional)
     * @type {number}
     * @default 10
     */
    "amountOfItems":'amountOfItems'*
     * The current level of subcomponents. Defaults to 0. (optional)
     * @type {number}
     * @default 0
     */
    "currentLevelOfS'currentLevelOfSubcomponents'*
     * Determines the default time to live (TTL) for entries in the IndexedDB. Defaults to 24 hours. Units are in milliseconds. (optional)
     * @type {number}
     * @default 24 * 60 * 60 * 1000
     */
    "defaultTTL": nu'defaultTTL'*
     * Determines whether components should be emphasized towards their surrounding by border and shadow. If set to true, border and shadows will be shown around the component. It not set, the component won't be surrounded by border and shadow. (optional)
     * @type {boolean}
     * @default true
     */
    "emphasizeCompon'emphasizeComponent'**
     * Initial height of the component (e.g. '300px', '50vh'). If not set, defaults to 300px.
     * @type {string}
     */
    "height"?: strin'height'**
     * Determines whether subcomponents should generally be shown or not. If set to true, the component won't show any subcomponents. If not set, the component will show subcomponents if the current level of subcomponents is not the total level of subcomponents or greater. (optional)
     * @type {boolean}
     */
    "hideSubcomponen'hideSubcomponents'**
     * The total number of levels of subcomponents to show. Defaults to 1. (optional)
     * @type {number}
     * @default 1
     */
    "levelOfSubcompo'levelOfSubcomponents'*
     * Determines whether the component is open or not by default. (optional)
     * @type {boolean}
     */
    "openByDefault":'openByDefault'**
     * A stringified JSON object containing settings for this component. The resulting object is passed to every subcomponent, so that every component has the same settings. Values and the according type are defined by the components themselves. (optional)  Schema: ```typescript {  type: string,  values: {   name: string,   value: any  }[] }[] ```
     * @type {string}
     * @default '[]'
     */
    "settings": stri'settings'*
     * Determines whether on the top level the copy button is shown. If set to true, the copy button is shown also on the top level. It not set, the copy button is only shown for sub-components. (optional)
     * @type {boolean}
     * @default true
     */
    "showTopLevelCop'showTopLevelCopy'**
     * Updates the component sizing and styling based on the expanded state This method is now handled by the pid-collapsible component
     */
    "updateComponent'updateComponentSizing'void>;
    /**
     * The value to parse, evaluate and render.
     * @type {string}
     */
    "value": string;'value'*
     * Initial width of the component (e.g. '500px', '50%'). If not set, defaults to 500px on large screens, 400px on medium screens, and 300px on small screens.
     * @type {string}
     */
    "width"?: string'width'  interface PidDataTable {
    /**
     * Current level of subcomponents
     * @default 0
     */
    "currentLevelOfS'currentLevelOfSubcomponents'*
     * Current page (0-based index)
     * @default 0
     */
    "currentPage": n'currentPage'*
     * Whether to hide subcomponents
     * @default false
     */
    "hideSubcomponen'hideSubcomponents'**
     * Array of items to display in the table
     * @default []
     */
    "items": Foldabl'items';
    /**
     * Number of items to show per page
     * @default 10
     */
    "itemsPerPage": 'itemsPerPage'*
     * Total level of subcomponents
     * @default 1
     */
    "levelOfSubcompo'levelOfSubcomponents'*
     * Whether to load subcomponents
     * @default false
     */
    "loadSubcomponen'loadSubcomponents'**
     * Available page sizes
     * @default [5, 10, 25, 50, 100]
     */
    "pageSizes": num'pageSizes'/**
     * Settings to pass to subcomponents
     * @default '[]'
     */
    "settings": stri'settings' interface PidPagination {
    /**
     * Current page (0-based index)
     * @default 0
     */
    "currentPage": n'currentPage'*
     * Number of items per page
     * @default 10
     */
    "itemsPerPage": 'itemsPerPage'*
     * Available page sizes
     * @default [5, 10, 25, 50, 100]
     */
    "pageSizes": num'pageSizes'/**
     * Total number of items
     * @default 0
     */
    "totalItems": nu'totalItems' interface PidTooltip {
    /**
     * The maximum height of the tooltip
     * @default '150px'
     */
    "maxHeight": str'maxHeight'*
     * The maximum width of the tooltip
     * @default '250px'
     */
    "maxWidth": stri'maxWidth'*
     * The position of the tooltip
     * @default 'top'
     */
    "position": 'top'position'm' | 'left' | 'right';
    /**
     * The text to display in the tooltip
     */
    "text": string;
'text'}
export interface PidCollapsibleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPidCollapsibleElement;
}
export interface PidDataTableCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPidDataTableElement;
}
export interface PidPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPidPaginationElement;
}
declare global {
    interface HTMLColorHighlightElement extends Components.ColorHighlight, HTMLStencilElement {
    }
    var HTMLColorHighlightElement: {
        prototype: HTMLColorHighlightElement;
        new (): HTMLColorHighlightElement;
    };
    interface HTMLCopyButtonElement extends Components.CopyButton, HTMLStencilElement {
    }
    var HTMLCopyButtonElement: {
        prototype: HTMLCopyButtonElement;
        new (): HTMLCopyButtonElement;
    };

  interface HTMLJsonViewerElement extends Components.JsonViewer, HTMLStencilElement {
  }

  var HTMLJsonViewerElement: {
    prototype: HTMLJsonViewerElement;
    new(): HTMLJsonViewerElement;
  };
    interface HTMLLocaleVisualizationElement extends Components.LocaleVisualization, HTMLStencilElement {
    }
    var HTMLLocaleVisualizationElement: {
        prototype: HTMLLocaleVisualizationElement;
        new (): HTMLLocaleVisualizationElement;
    };

  interface HTMLPidActionsElement extends Components.PidActions, HTMLStencilElement {
  }

  var HTMLPidActionsElement: {
    prototype: HTMLPidActionsElement;
    new(): HTMLPidActionsElement;
  };

  interface HTMLPidCollapsibleElementEventMap {
    'collapsibleToggle': boolean;
  }

  interface HTMLPidCollapsibleElement extends Components.PidCollapsible, HTMLStencilElement {
    addEventListener<K extends keyof HTMLPidCollapsibleElementEventMap>(type: K, listener: (this: HTMLPidCollapsibleElement, ev: PidCollapsibleCustomEvent<HTMLPidCollapsibleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;

    addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;

    addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;

    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;

    removeEventListener<K extends keyof HTMLPidCollapsibleElementEventMap>(type: K, listener: (this: HTMLPidCollapsibleElement, ev: PidCollapsibleCustomEvent<HTMLPidCollapsibleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;

    removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;

    removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;

    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
  }

  var HTMLPidCollapsibleElement: {
    prototype: HTMLPidCollapsibleElement;
    new(): HTMLPidCollapsibleElement;
  };
    interface HTMLPidComponentElement extends Components.PidComponent, HTMLStencilElement {
    }
    var HTMLPidComponentElement: {
        prototype: HTMLPidComponentElement;
        new (): HTMLPidComponentElement;
    };

  interface HTMLPidDataTableElementEventMap {
    'pageChange': number;
    'itemsPerPageChange': number;
  }

  interface HTMLPidDataTableElement extends Components.PidDataTable, HTMLStencilElement {
    addEventListener<K extends keyof HTMLPidDataTableElementEventMap>(type: K, listener: (this: HTMLPidDataTableElement, ev: PidDataTableCustomEvent<HTMLPidDataTableElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;

    addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;

    addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;

    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;

    removeEventListener<K extends keyof HTMLPidDataTableElementEventMap>(type: K, listener: (this: HTMLPidDataTableElement, ev: PidDataTableCustomEvent<HTMLPidDataTableElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;

    removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;

    removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;

    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
  }

  var HTMLPidDataTableElement: {
    prototype: HTMLPidDataTableElement;
    new(): HTMLPidDataTableElement;
  };

  interface HTMLPidPaginationElementEventMap {
    'pageChange': number;
    'itemsPerPageChange': number;
  }

  interface HTMLPidPaginationElement extends Components.PidPagination, HTMLStencilElement {
    addEventListener<K extends keyof HTMLPidPaginationElementEventMap>(type: K, listener: (this: HTMLPidPaginationElement, ev: PidPaginationCustomEvent<HTMLPidPaginationElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;

    addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;

    addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;

    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;

    removeEventListener<K extends keyof HTMLPidPaginationElementEventMap>(type: K, listener: (this: HTMLPidPaginationElement, ev: PidPaginationCustomEvent<HTMLPidPaginationElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;

    removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;

    removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;

    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
  }

  var HTMLPidPaginationElement: {
    prototype: HTMLPidPaginationElement;
    new(): HTMLPidPaginationElement;
  };

  interface HTMLPidTooltipElement extends Components.PidTooltip, HTMLStencilElement {
  }

  var HTMLPidTooltipElement: {
    prototype: HTMLPidTooltipElement;
    new(): HTMLPidTooltipElement;
  };
    interface HTMLElementTagNameMap {
        "color-highlight": HTMLColorHighlightElement;
        "copy-button": HTMLCopyButtonElement;
      'json-viewer': HTMLJsonViewerElement;
        "locale-visualization": HTMLLocaleVisualizationElement;
      'pid-actions': HTMLPidActionsElement;
      'pid-collapsible': HTMLPidCollapsibleElement;
        "pid-component": HTMLPidComponentElement;
      'pid-data-table': HTMLPidDataTableElement;
      'pid-pagination': HTMLPidPaginationElement;
      'pid-tooltip': HTMLPidTooltipElement;
    }
}
declare namespace LocalJSX {
    interface ColorHighlight {
        /**
          * The text to highlight.
          * @type {string}
         */
        "text": string;
    }
    interface CopyButton {
        /**
          * The value to copy to the clipboard.
          * @type {string}
          * @public
         */
        "value": string;
    }

  interface JsonViewer {
    /**
     * The JSON data to display. Can be a JSON string or a JavaScript object.
     */
    'data'?: string | object;
    /**
     * Set to true to open all nodes in tree view initially.
     * @default false
     */
    'expandAll'?: boolean;
    /**
     * Maximum height of the viewer in pixels. Set to 0 for no limit.
     * @default 500
     */
    'maxHeight'?: number;
    /**
     * Set to true to enable line numbers in code view.
     * @default true
     */
    'showLineNumbers'?: boolean;
    /**
     * Theme for syntax highlighting. Options: 'light' or 'dark'.
     * @default 'light'
     */
    'theme'?: 'light' | 'dark';
    /**
     * Initial view mode for the JSON data. Can be 'tree' or 'code'.
     * @default 'tree'
     */
    'viewMode'?: 'tree' | 'code';
  }
    interface LocaleVisualization {
        /**
          * The locale to visualize.
          * @type {string}
          * @public
         */
        "locale": string;
        /**
          * Whether to show the flag of the region.
          * @type {boolean}
         * @public
         * @default true
         */
        "showFlag"?: boolean;
    }

  interface PidActions {
    /**
     * Array of actions to display
     * @default []
     */
    'actions'?: FoldableAction[];
  }

  interface PidCollapsible {
    /**
     * Whether to emphasize the component with border and shadow
     * @default false
     */
    'emphasize'?: boolean;
    /**
     * Whether the component is in expanded mode (full size)
     * @default false
     */
    'expanded'?: boolean;
    /**
     * Initial height when expanded
     */
    'initialHeight'?: string;
    /**
     * Initial width when expanded
     */
    'initialWidth'?: string;
    /**
     * Line height for collapsed state
     * @default 24
     */
    'lineHeight'?: number;
    /**
     * Event emitted when the collapsible is toggled
     */
    'onCollapsibleToggle'?: (event: PidCollapsibleCustomEvent<boolean>) => void;
    /**
     * Whether the collapsible is open by default
     * @default false
     */
    'open'?: boolean;
    /**
     * Whether to show the footer section
     * @default false
     */
    'showFooter'?: boolean;
  }
    interface PidComponent {
        /**
          * The number of items to show in the table per page. Defaults to 10. (optional)
          * @type {number}
         * @default 10
         */
        "amountOfItems"?: number;
        /**
          * The current level of subcomponents. Defaults to 0. (optional)
          * @type {number}
         * @default 0
         */
        "currentLevelOfSubcomponents"?: number;
        /**
          * Determines the default time to live (TTL) for entries in the IndexedDB. Defaults to 24 hours. Units are in milliseconds. (optional)
          * @type {number}
          * @default 24 * 60 * 60 * 1000
         */
        "defaultTTL"?: number;
        /**
          * Determines whether components should be emphasized towards their surrounding by border and shadow. If set to true, border and shadows will be shown around the component. It not set, the component won't be surrounded by border and shadow. (optional)
          * @type {boolean}
         * @default true
         */
        "emphasizeComponent"?: boolean;
        /**
         * Initial height of the component (e.g. '300px', '50vh'). If not set, defaults to 300px.
         * @type {string}
         */
        'height'?: string;
      /**
          * Determines whether subcomponents should generally be shown or not. If set to true, the component won't show any subcomponents. If not set, the component will show subcomponents if the current level of subcomponents is not the total level of subcomponents or greater. (optional)
          * @type {boolean}
         */
        "hideSubcomponents"?: boolean;
        /**
          * The total number of levels of subcomponents to show. Defaults to 1. (optional)
          * @type {number}
         * @default 1
         */
        "levelOfSubcomponents"?: number;
        /**
          * Determines whether the component is open or not by default. (optional)
          * @type {boolean}
         */
        "openByDefault"?: boolean;
        /**
          * A stringified JSON object containing settings for this component. The resulting object is passed to every subcomponent, so that every component has the same settings. Values and the according type are defined by the components themselves. (optional)  Schema: ```typescript {  type: string,  values: {   name: string,   value: any  }[] }[] ```
          * @type {string}
         * @default '[]'
         */
        "settings"?: string;
        /**
          * Determines whether on the top level the copy button is shown. If set to true, the copy button is shown also on the top level. It not set, the copy button is only shown for sub-components. (optional)
          * @type {boolean}
         * @default true
         */
        "showTopLevelCopy"?: boolean;
        /**
          * The value to parse, evaluate and render.
          * @type {string}
         */
        "value"?: string;
      /**
       * Initial width of the component (e.g. '500px', '50%'). If not set, defaults to 500px on large screens, 400px on medium screens, and 300px on small screens.
       * @type {string}
       */
      'width'?: string;
    }

  interface PidDataTable {
    /**
     * Current level of subcomponents
     * @default 0
     */
    'currentLevelOfSubcomponents'?: number;
    /**
     * Current page (0-based index)
     * @default 0
     */
    'currentPage'?: number;
    /**
     * Whether to hide subcomponents
     * @default false
     */
    'hideSubcomponents'?: boolean;
    /**
     * Array of items to display in the table
     * @default []
     */
    'items'?: FoldableItem[];
    /**
     * Number of items to show per page
     * @default 10
     */
    'itemsPerPage'?: number;
    /**
     * Total level of subcomponents
     * @default 1
     */
    'levelOfSubcomponents'?: number;
    /**
     * Whether to load subcomponents
     * @default false
     */
    'loadSubcomponents'?: boolean;
    /**
     * Event emitted when items per page changes
     */
    'onItemsPerPageChange'?: (event: PidDataTableCustomEvent<number>) => void;
    /**
     * Event emitted when page changes
     */
    'onPageChange'?: (event: PidDataTableCustomEvent<number>) => void;
    /**
     * Available page sizes
     * @default [5, 10, 25, 50, 100]
     */
    'pageSizes'?: number[];
    /**
     * Settings to pass to subcomponents
     * @default '[]'
     */
    'settings'?: string;
  }

  interface PidPagination {
    /**
     * Current page (0-based index)
     * @default 0
     */
    'currentPage'?: number;
    /**
     * Number of items per page
     * @default 10
     */
    'itemsPerPage'?: number;
    /**
     * Event emitted when items per page changes
     */
    'onItemsPerPageChange'?: (event: PidPaginationCustomEvent<number>) => void;
    /**
     * Event emitted when page changes
     */
    'onPageChange'?: (event: PidPaginationCustomEvent<number>) => void;
    /**
     * Available page sizes
     * @default [5, 10, 25, 50, 100]
     */
    'pageSizes'?: number[];
    /**
     * Total number of items
     * @default 0
     */
    'totalItems'?: number;
  }

  interface PidTooltip {
    /**
     * The maximum height of the tooltip
     * @default '150px'
     */
    'maxHeight'?: string;
    /**
     * The maximum width of the tooltip
     * @default '250px'
     */
    'maxWidth'?: string;
    /**
     * The position of the tooltip
     * @default 'top'
     */
    'position'?: 'top' | 'bottom' | 'left' | 'right';
    /**
     * The text to display in the tooltip
     */
    'text': string;
  }
    interface IntrinsicElements {
        "color-highlight": ColorHighlight;
        "copy-button": CopyButton;
      'json-viewer': JsonViewer;
        "locale-visualization": LocaleVisualization;
      'pid-actions': PidActions;
      'pid-collapsible': PidCollapsible;
        "pid-component": PidComponent;
      'pid-data-table': PidDataTable;
      'pid-pagination': PidPagination;
      'pid-tooltip': PidTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "color-highlight": LocalJSX.ColorHighlight & JSXBase.HTMLAttributes<HTMLColorHighlightElement>;
            "copy-button": LocalJSX.CopyButton & JSXBase.HTMLAttributes<HTMLCopyButtonElement>;
          'json-viewer': LocalJSX.JsonViewer & JSXBase.HTMLAttributes<HTMLJsonViewerElement>;
            "locale-visualization": LocalJSX.LocaleVisualization & JSXBase.HTMLAttributes<HTMLLocaleVisualizationElement>;
          'pid-actions': LocalJSX.PidActions & JSXBase.HTMLAttributes<HTMLPidActionsElement>;
          'pid-collapsible': LocalJSX.PidCollapsible & JSXBase.HTMLAttributes<HTMLPidCollapsibleElement>;
            "pid-component": LocalJSX.PidComponent & JSXBase.HTMLAttributes<HTMLPidComponentElement>;
          'pid-data-table': LocalJSX.PidDataTable & JSXBase.HTMLAttributes<HTMLPidDataTableElement>;
          'pid-pagination': LocalJSX.PidPagination & JSXBase.HTMLAttributes<HTMLPidPaginationElement>;
          'pid-tooltip': LocalJSX.PidTooltip & JSXBase.HTMLAttributes<HTMLPidTooltipElement>;
        }
    }
}
